### ISSUE TITLE
Fix building this project and make it robust

### ISSUE THREAD

**Issue by bessarabov** [metacpan/metacpan-docker#10]
The current version of metacpan-docker is completly broken. It worked fine when it was createad (about a year ago), but now it does not work. The problem is that the surrounding world has changed. Some packages disappeared (see #9 ), some new dependencies appeared ( see #6 )

This project has to be fixed. The main idea that we need to create this project in the way the changes in the surrounding world should not matter. We need to explicitly specify all the dependencies and versions.

The other thing that I want to be done is to simplify the process of running this project.

So, this is the plan:
- use docker-compose
- remove elasticsearch Dockerfile and to use elasticsearch image from the docker hub
- explicitly specify git commits from cpan-api and metacpan-web project

I'm going to implement it in the separate git branch `dev`

**Comment by bessarabov** [comment]
I did some work for this issue. The current HEAD of `dev` git branch is 6058ea3c0b0a19e938670a6918b2923c3faadb91

But now cpan-api shows error:

> Error while loading /app/app.psgi: Couldn't instantiate component "MetaCPAN::Server::Model::Source", "Attribute (cpan) does not pass the type constraint because: Validation failed for 'MooseX::Types::Path::Class::MoreCoercions::Dir' with value undef at constructor MetaCPAN::Server::Model::Source::new (defined at /app/lib/MetaCPAN/Server/Model/Source.pm line 86) line 38.
    
Full log — https://gist.github.com/bessarabov/cb18d69f289236c696e8

**Comment by JaSei** [comment]
> explicitly specify git commits from cpan-api and metacpan-web project
I think will be better use tags (I know its same, but name is better then hash) or releases for this...

**Comment by bessarabov** [comment]
> btw. docker-compose is good for testing, but maybe not for production

Correct. Metacpan does not use neither docker-compose, nor docker in production. Here is the metacpan repo with puppet configuration for development, test and production servers https://github.com/CPAN-API/metacpan-puppet

The current project metacpan-docker is an experiment to create development environment in docker.

**Comment by bessarabov** [comment]
> > explicitly specify git commits from cpan-api and metacpan-web project
> I think will be better use tags (I know its same, but name is better then hash) or releases for this...

Yep. I would be glad to use tags instead of commites. But neither cpan-api, nor metacpan-web use tags to mark releases:

 * https://github.com/CPAN-API/cpan-api/tags
 * https://github.com/CPAN-API/cpan-api/tags
