### ISSUE TITLE
bin/metacpan-docker localapi up: Couldn't connect to Docker daemon

### ISSUE THREAD

**Issue by hakonhagland** [metacpan/metacpan-docker#43]
Hello, I am on Ubuntu 19.04. Continuing from https://github.com/metacpan/metacpan-developer/issues/45 I am trying to get started running MetaCPAN with `docker` now. First I ran:
```
sudo snap install docker
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
git clone https://github.com/metacpan/metacpan-docker.git
cd metacpan-docker/
bin/metacpan-docker init
```

Then I tried:

```
$ bin/metacpan-docker localapi up
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
$ docker-machine start default
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
```

```

**Comment by oalders** [comment]
Could you see if this update fixes your issue? https://github.com/metacpan/metacpan-docker/pull/44/files

**Comment by hakonhagland** [comment]
Ok I did some trial and error, and I am not sure what actually made it work. But, after checking out these:

https://github.com/docker/machine/issues/4590
https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

I ended up doing:
```
sudo groupadd docker
sudo gpasswd -a $USER docker
newgrp docker
```
and then restarted my machine (`sudo reboot`).
and then I could run `bin/metacpan-docker localapi up` without errors..
