### ISSUE TITLE
Provide a way to update all git repo

### ISSUE THREAD

**Issue by atoomic** [metacpan/metacpan-docker#53]
When initializing the repo using `bin/metacpan-docker` we have the last status from upstream.
But over time, we might end up working on one or more branches and trend to leave the other repo behind.

We should consider adding new verbs to `bin/metacpan-docker` like
* `pull` to pull from every repo [and maybe do nothing if not clean, and warn when not on master]
* `reset` switch to master and hard reset to upstream/master after having pull from it

**Comment by oalders** [comment]
I think this was closed via #54
