### ISSUE TITLE
Service 'web' failed to build

### ISSUE THREAD

**Issue by srchulo** [metacpan/metacpan-docker#67]
I am running these steps from the README:

```
git clone https://github.com/metacpan/metacpan-docker.git
cd metacpan-docker
bin/metacpan-docker init
```

And then I run:

`bin/metacpan-docker localapi up`

However, the command fails and I get this output:

```
E: Version '10.17.0-1nodesource1' for 'nodejs' was not found
ERROR: Service 'web' failed to build: The command '/bin/bash -o pipefail -c curl -sL https://deb.nodesource.com/setup_10.x | bash     && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list     && apt-get update     && apt-get install -y -f --no-install-recommends nodejs=10.17.0-1nodesource1 yarn=1.19.2-1     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by oalders** [comment]
@ssoriche any idea why `localapi` fails to start because of a `metacpan-web` error?

**Comment by oalders** [comment]
@srchulo if you're motivated to fix the web end of things, you could take a look at https://github.com/metacpan/metacpan-web/blob/master/Dockerfile 

I think the choice of node version is somewhat arbitrary.

**Comment by srchulo** [comment]
@oalders replacing `nodejs=10.17.0-1nodesource1` with `nodejs` allowed the image to be built past that step. The version of nodejs that it did install for me was `10.18.1-1nodesource1`, in case it should be pinned to something.

I did then run into issues installing the CPAN modules, but that's probably a separate issue:

```
fork: Cannot allocate memory at /usr/local/lib/perl5/site_perl/5.30.1/Command/Runner.pm line 174.
FAIL install HTML-Tree-5.07
# more fails
```

**Comment by oalders** [comment]
@srchulo thanks.  If you want to send a PR for the `nodejs` changes, we can get that merged. 

For the CPAN modules, what's the installer being used?  If it's `cpm` you could try setting `--workers` to a lower number (it defaults to 5) to see if that helps with memory allocation.

**Comment by srchulo** [comment]
@oalders pull request created.

And yeah, it was using `cpm`. This time it seemed do install fine, so I don't know what the issue was before.
