### ISSUE TITLE
Volume metacpan_git_shared declared as external, but could not be found

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-docker#68]
```
$ ./bin/metacpan-docker up metacpan-api
ERROR: Volume metacpan_git_shared declared as external, but could not be found. Please create the volume manually using `docker volume create --name=metacpan_git_shared` and try again.
```

Would be helpful if `bin/metacpan-docker` took care of creating this volume.

**Comment by waterkip** [comment]
For external volumes (and networks) you need to create it first. You need to remove the `external: true` from docker-compose.yml (or override) to make for docker-compose to create the volume within the project. Or create it manually.

I cannot find the volume declaration in the git repo, is it removed now?

**Comment by oalders** [comment]
It looks like this was meant to address the creation: https://github.com/metacpan/metacpan-docker/commit/7058539c631a7a079a7eb139f92332669e4510f9

Maybe I didn't run `./bin/metacpan-docker init` as a first step here.
