### ISSUE TITLE
elasticsearch version

### ISSUE THREAD

**Issue by JaSei** [metacpan/metacpan-docker#9]
Hello,
you use elasticsearch 0.9, but in docker.hub is lowest version 1.3 (and latest 1.7)

if you see to documentation - api is changed ([0.9](https://www.elastic.co/guide/en/elasticsearch/reference/0.90/cluster-nodes-stats.html) vs [1.3](https://www.elastic.co/guide/en/elasticsearch/reference/1.3/cluster-nodes-info.html)) and now failing cpan-api part

```
carton exec bin/metacpan mapping --delete
2015/10/24 22:53:55 I mapping: Putting mapping to ElasticSearch server
[ERROR] ** ElasticSearch::Error::NoServers at /cpan-api/local/lib/perl5/ElasticSearch/Transport.pm line 268 :
Could not retrieve a list of active servers:
    [ERROR] ** ElasticSearch::Error::Request at /cpan-api/local/lib/perl5/ElasticSearch/Transport/HTTPTiny.pm line 75 :
    Bad Request (400)

    With vars:{
      'request' => {
        'cmd' => '/_cluster/nodes',
        'qs' => {
          'http' => 1
        },
        'method' => 'GET'
      },
      'status_msg' => 'Bad Request',
      'status_code' => 400,
      'content' => 'No handler found for uri [/_cluster/nodes?http=1] and method [GET]',
      'server' => 'elasticsearch:9200'
    }



With vars:{
  'servers' => [
    'elasticsearch:9200'
  ]
}
```

solutions:
- using new elasticsearch
- change in documentation elasticsearch docker to barnybug/elasticsearch:0.90.13 (for example - this works)

thanks

**Comment by oalders** [comment]
@JaSei thanks for this.  The Elasticsearch is a work in progress with no foreseeable date of completion.  We'd accept a pull request which forces a downgraded version of Elasticsearch.
